### PR TITLE
Merge Sort in Python

### PR DESCRIPTION
**Pull request by SarthakSharma660**
a programme for merge sort.

### CODE REVIEW

**Comment by c0sm0void** [comment]
please add detail in contributer.md

**Comment by SarthakSharma660** [comment]
@c0sm0void i am new to this so i don't know how to change contribute.md can you please guide me

**Comment by c0sm0void** [comment]
> @c0sm0void i am new to this so i don't know how to change contribute.md can you please guide me

go to contributers.md and at last of the file add your details and commit

**Comment by SarthakSharma660** [comment]
@c0sm0void please have a look i have done it

**Comment by SarthakSharma660** [comment]
hi @c0sm0void my pull request was merged but still, it is not reflecting on my hacktoberfest profile, do you know the reason?

**Pull request merged**
